project_name: terraform-registry
release:
    disable: true
builds:
    - id: registry
      goos:
        - linux
      goarch:
        - amd64
      main: ./cmd/registry/
      binary: registry
      env:
        - CGO_ENABLED=0
checksum:
    name_template: checksums.txt
dockers:
    - ids:
        - registry
      goos: linux
      goarch: amd64
      dockerfile: packaging/docker/Dockerfile
      image_templates:
        - 'postfinance/terraform-registry:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
        - 'postfinance/terraform-registry:{{ .Major }}.{{ .Minor }}'
        - 'postfinance/terraform-registry:{{ .Major }}'
        - 'postfinance/terraform-registry:latest'
      extra_files:
        - packaging/docker/docker-entrypoint.sh
      build_flag_templates:
        - --label=org.opencontainers.image.version={{ .Version }}
        - --label=org.opencontainers.image.revision={{ .ShortCommit }}
        - --label=org.opencontainers.image.created={{ .Date }}
        - --label=org.opencontainers.image.vendor=PostFinance AG
